Real Money damage boost
tadpoleloop/idle_apocalypse_event_planner pull request #30
Opened 2023-05-05 18:22 UTC by kiaen1

I added the real money damage boost to the calcs, as a way for people to judge if it's worth it for them.

2023-05-05 20:26 UTC, tadpoleloop commented on state.pyx
> +        self.boost_level = state.boost_level
Repeated Lines

2023-05-05 20:38 UTC, tadpoleloop requested changes
Besides the small nit about a repeated line, looks good to me.

2023-05-05 20:46 UTC, tadpoleloop commented on state.pyx
> +        self.boost_level = 1
default boost_level should be 0

2023-05-05 21:21 UTC, kiaen1 commented
Alright, it's been pushed.

2023-05-06 02:40 UTC, tadpoleloop approved these changes

2023-05-06 02:40 UTC, merged